# Generated by Django 4.0 on 2022-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_file', models.FileField(upload_to='customer_files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=50)),
            ],
        ),
    ]
